# This file intentionally left minimal.
# Resolve target entity mapping for HasAccessTokensInterface is registered dynamically
# from the bundle configuration (sanctum.owner_class) by AccessTokenMappingPass.
# Do not rely on a static mapping here to avoid surprising overrides in the host app.

doctrine:
  orm:
    resolve_target_entities:
      Jonston\SanctumBundle\Contract\HasAccessTokensInterface: '%sanctum.owner_class%'
