services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Jonston\SanctumBundle\Service\TokenService:
    arguments:
      $tokenRepository: '@Jonston\SanctumBundle\Repository\PersonalAccessTokenRepository'
      $tokenHasher: '@Jonston\SanctumBundle\Service\TokenHasher'

  Jonston\SanctumBundle\Security\TokenAuthenticator:
    arguments:
      $tokenService: '@Jonston\SanctumBundle\Service\TokenService'

  Jonston\SanctumBundle\Repository\PersonalAccessTokenRepository:
    arguments: ['@doctrine']
