services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # Основной сервис для работы с токенами
  Jonston\SanctumBundle\Service\TokenService:
    arguments:
      $tokenRepository: '@Jonston\SanctumBundle\Repository\PersonalAccessTokenRepository'

  # Аутентификатор токенов
  Jonston\SanctumBundle\Security\TokenAuthenticator:
    arguments:
      $tokenService: '@Jonston\SanctumBundle\Service\TokenService'

  # Адаптер пользователя для Security
  Jonston\SanctumBundle\Security\UserAdapter:

  # Репозиторий токенов
  Jonston\SanctumBundle\Repository\PersonalAccessTokenRepository:
    arguments: ['@doctrine']

  # Устаревшие сервисы для обратной совместимости (можно удалить позже)
  Jonston\SanctumBundle\Service\TokenHasher:

  Jonston\SanctumBundle\Service\TokenManager:
    arguments:
      $tokenRepository: '@Jonston\SanctumBundle\Repository\PersonalAccessTokenRepository'
      $em: '@doctrine.orm.entity_manager'
      $tokenHasher: '@Jonston\SanctumBundle\Service\TokenHasher'
