services:
  # Auto-configure services
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # Register all services in the bundle automatically
  Jonston\SanctumBundle\:
    resource: '../../*'
    exclude:
      - '../../{Entity,Tests,DependencyInjection}'
      - '../../**/*Interface.php'

  # Make core services public for easy access
  Jonston\SanctumBundle\Service\TokenHasher:
    public: true

  Jonston\SanctumBundle\Service\TokenManager:
    public: true

  # Repository needs explicit doctrine registry
  Jonston\SanctumBundle\Repository\PersonalAccessTokenRepository:
    public: true
    arguments:
      $registry: '@doctrine'

  # Security authenticator with optional user provider
  Jonston\SanctumBundle\Security\TokenAuthenticator:
    public: true
    arguments:
      $userProvider: null
    tags:
      - { name: 'security.authenticator' }
