services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Jonston\SanctumBundle\Security\TokenAuthenticator:
    arguments:
      $tokenRepository: '@Jonston\SanctumBundle\Repository\PersonalAccessTokenRepository'
      $tokenManager: '@Jonston\SanctumBundle\Service\TokenManager'
      $userProvider: null  # или укажите конкретный UserProvider если нужен

  Jonston\SanctumBundle\Service\TokenHasher:

  # Основной сервис
  Jonston\SanctumBundle\Service\TokenManager:
    arguments:
      $tokenRepository: '@Jonston\SanctumBundle\Repository\PersonalAccessTokenRepository'
      $em: '@doctrine.orm.entity_manager'
      $tokenHasher: '@Jonston\SanctumBundle\Service\TokenHasher'

  # Репозиторий
  Jonston\SanctumBundle\Repository\PersonalAccessTokenRepository:
    factory: ['@doctrine', 'getRepository']
    arguments: [
      'Jonston\SanctumBundle\Entity\PersonalAccessToken'
    ]