services:
  # Auto-configure services
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # Register all services in the bundle
  Jonston\SanctumBundle\:
    resource: '../../*'
    exclude: '../../{Entity,Tests,DependencyInjection}'

  # Core services
  Jonston\SanctumBundle\Service\TokenHasher:
    public: true

  Jonston\SanctumBundle\Service\TokenManager:
    public: true

  Jonston\SanctumBundle\Repository\PersonalAccessTokenRepository:
    public: true
    arguments:
      $registry: '@doctrine'

  # Security authenticator - UserProvider is optional
  Jonston\SanctumBundle\Security\TokenAuthenticator:
    public: true
    arguments:
      $tokenRepository: '@Jonston\SanctumBundle\Repository\PersonalAccessTokenRepository'
      $tokenManager: '@Jonston\SanctumBundle\Service\TokenManager'
      $userProvider: '@?security.user.provider.concrete.users'
    tags:
      - { name: security.authenticator }
